<a href="https://colab.research.google.com/github/Recollectionss/numeral-methods/blob/main/lab_2/lab_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np

BORDER_LENGTH = 100

def print_border():
    print("-" * BORDER_LENGTH)

def create_matrix_and_vector(n):
    A = np.zeros((n, n))
    # b = np.random.randint(1, 10, size=n)
    b = np.array([7, 1, 9, 4])

    for i in range(n):
        A[i][i] = 10  # Діагональні елементи для домінантності

        if i > 0:
            A[i][i-1] = 2  # Піддіагональні елементи
        if i < n - 1:
            A[i][i+1] = 2  # Наддіагональні елементи

    return A, b

def check_gauss(matr):
    print("\nChecking if the system can be solved by Gauss method:")
    det = np.linalg.det(matr)
    print(f"Determinant: {det:.4f}")

    if abs(det) < 1e-10:
        print("Determinant is too close to 0 -> cannot be solved")
        print_border()
        return False

    print("Determinant is non-zero, solving can proceed.")
    print_border()
    return True

def gauss(A, b):
    print("=== GAUSS METHOD ===\n")

    if not check_gauss(A):
        return np.zeros(len(b))

    matr_len = len(b)
    for i in range(matr_len):
        p = np.identity(matr_len)
        m = np.identity(matr_len)

        print(f"\nStep {i + 1}:")
        print("Current A matrix:\n", A)
        print("\nCurrent b vector:\n", b)

        max_row = np.argmax(np.abs(A[i:matr_len, i])) + i
        if np.abs(A[max_row, i]) < 1e-10:  # Додано перевірку на нульовий опорний елемент
            print("Pivot element is too small, system may be singular")
            return np.zeros(len(b))

        p[[i, max_row]] = p[[max_row, i]]
        print("\nP matrix (permutation):\n", p)

        A = np.matmul(p, A)
        b = np.matmul(p, b)

        for j in range(matr_len):
            if j < i:
                m[j, i] = 0
            elif j == i:
                m[j, i] = 1 / A[j, i]
            else:
                m[j, i] = -A[j, i] / A[i, i]

        print("\nM matrix (elimination):\n", m)
        print_border()

        A = np.matmul(m, A)
        b = np.matmul(m, b)

    print("\nFinal transformed A matrix:\n", A)
    print("\nFinal transformed b vector:\n", b)
    print_border()

    x = np.zeros(matr_len)
    for i in range(matr_len - 1, -1, -1):
        x[i] = b[i]
        for j in range(i + 1, matr_len):
            x[i] -= A[i, j] * x[j]

    return x

def gauss_extended(A, b):
    print("=== GAUSS METHOD (Extended) ===\n")

    augmented_matrix = np.hstack((A, b.reshape(-1, 1)))

    for i in range(len(A)):
        max_row = np.argmax(np.abs(augmented_matrix[i:, i])) + i
        if np.abs(augmented_matrix[max_row, i]) < 1e-10:
            print("Pivot element is too small, system may be singular")
            return np.zeros(len(b))

        augmented_matrix[[i, max_row]] = augmented_matrix[[max_row, i]]

        for j in range(i + 1, len(A)):
            ratio = augmented_matrix[j, i] / augmented_matrix[i, i]
            augmented_matrix[j] -= ratio * augmented_matrix[i]

    x = np.zeros(len(b))
    for i in range(len(A) - 1, -1, -1):
        x[i] = (augmented_matrix[i, -1] - np.dot(augmented_matrix[i, i+1:len(A)], x[i+1:])) / augmented_matrix[i, i]

    return x

def tridiagonal_solver(A, b):
    n = len(b)
    c = np.zeros(n - 1)
    d = np.zeros(n)

    for i in range(1, n):
        factor = A[i, i - 1] / A[i - 1, i - 1]
        A[i, i] -= factor * A[i - 1, i]
        b[i] -= factor * b[i - 1]

    d[-1] = b[-1] / A[-1, -1]
    for i in range(n - 2, -1, -1):
        d[i] = (b[i] - A[i, i + 1] * d[i + 1]) / A[i, i]

    return d

def is_diagonally_dominant(A):
    for i in range(len(A)):
        row_sum = np.sum(np.abs(A[i])) - np.abs(A[i, i])
        if np.abs(A[i, i]) <= row_sum:
            return False
    return True

def jacobi_method(A, b, epsilon=1e-9, max_iterations=1000):
    n = len(A)
    x0 = np.zeros(n)

    x = x0.copy()

    for iteration in range(max_iterations):
        x_new = np.zeros(n)
        for i in range(n):
            s = sum(A[i, j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i, i]

        if np.linalg.norm(x_new - x, np.inf) < epsilon:
            return x_new

        x = x_new

    return x

def inverse_matrix(A):
    n = A.shape[0]
    I = np.eye(n)  # Одинична матриця
    augmented_matrix = np.hstack((A, I))

    for i in range(n):
        max_row = np.argmax(np.abs(augmented_matrix[i:, i])) + i
        augmented_matrix[[i, max_row]] = augmented_matrix[[max_row, i]]

        for j in range(i + 1, n):
            ratio = augmented_matrix[j, i] / augmented_matrix[i, i]
            augmented_matrix[j] -= ratio * augmented_matrix[i]

    for i in range(n - 1, -1, -1):
        augmented_matrix[i] /= augmented_matrix[i, i]
        for j in range(i - 1, -1, -1):
            ratio = augmented_matrix[j, i]
            augmented_matrix[j] -= ratio * augmented_matrix[i]

    return augmented_matrix[:, n:]  # Повертаємо обернену матрицю

def main():
    A, b = create_matrix_and_vector(4)

    print("=== GENERATED MATRIX A ===\n", A)
    print("=== GENERATED VECTOR b ===\n", b)

    # Знаходимо обернену матрицю
    try:
        A_inv = inverse_matrix(A)
        print("\nInverse of matrix A:\n", A_inv)
    except np.linalg.LinAlgError:
        print("Matrix A is singular and cannot be inverted.")

    # Метод Гаусса для звичайної матриці
    solution_gauss = gauss(A.copy(), b.copy())
    print("\nSolution using Gauss method:\n", solution_gauss)

    # Метод Якобі
    solution_jacobi = jacobi_method(A.copy(), b.copy())
    print("\nSolution using Jacobi method:\n", solution_jacobi)

    # Метод прогонки
    solution_tridiagonal = tridiagonal_solver(A.copy(), b.copy())
    print("\nSolution using Tridiagonal method:\n", solution_tridiagonal)


if __name__ == "__main__":
    main()


=== GENERATED MATRIX A ===
 [[10.  2.  0.  0.]
 [ 2. 10.  2.  0.]
 [ 0.  2. 10.  2.]
 [ 0.  0.  2. 10.]]
=== GENERATED VECTOR b ===
 [7 1 9 4]

Inverse of matrix A:
 [[ 0.10435572 -0.02177858  0.00453721 -0.00090744]
 [-0.02177858  0.10889292 -0.02268603  0.00453721]
 [ 0.00453721 -0.02268603  0.10889292 -0.02177858]
 [-0.00090744  0.00453721 -0.02177858  0.10435572]]
=== GAUSS METHOD ===


Checking if the system can be solved by Gauss method:
Determinant: 8816.0000
Determinant is non-zero, solving can proceed.
----------------------------------------------------------------------------------------------------

Step 1:
Current A matrix:
 [[10.  2.  0.  0.]
 [ 2. 10.  2.  0.]
 [ 0.  2. 10.  2.]
 [ 0.  0.  2. 10.]]

Current b vector:
 [7 1 9 4]

P matrix (permutation):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

M matrix (elimination):
 [[ 0.1  0.   0.   0. ]
 [-0.2  1.   0.   0. ]
 [-0.   0.   1.   0. ]
 [-0.   0.   0.   1. ]]
-----------------------------------------