<a href="https://colab.research.google.com/github/Recollectionss/numeral-methods/blob/main/lab_3/lab_3_nm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

BORDER = "-"*60
SPACE = " "*15

# Функція для системи рівнянь F(x) = 0
def F(x, funcs):
    return np.array([f(x) for f in funcs])

# Функція для обчислення похідної phi(x) за допомогою числового диференціювання
def derivative_phi(x, C, funcs, h=1e-5):
    phi_x = phi(x, C, funcs)
    phi_x_h = phi(x + h, C, funcs)
    return (np.linalg.norm(phi_x_h - phi_x)) / h


# Якобіан функцій F(x) (матриця часткових похідних)
def jacobian(x, funcs, num_vars):
    jacobian_matrix = np.zeros((num_vars, num_vars))
    h = 1e-5  # Малий крок для обчислення похідних (для числового диференціювання)
    for i in range(num_vars):
        x_h = np.copy(x)
        x_h[i] += h  # Збільшуємо i-у змінну на малий крок
        jacobian_matrix[:, i] = (F(x_h, funcs) - F(x, funcs)) / h
    return jacobian_matrix

# Перетворення Phi(x) = x - C * F(x), де C - невироджена матриця
def phi(x, C, funcs):
    return x - C @ F(x, funcs)

def simple_iteration_method(x0, funcs, tol=1e-6, max_iter=100):
    print(f"{BORDER} \n {SPACE}Метод простої ітерації")
    x = np.copy(x0)
    num_vars = len(x)
    iterations = 0

    # Початковий Якобіан для обчислення C
    C = np.linalg.inv(jacobian(x, funcs, num_vars))  # Матриця C
    print(f"Початковий Якобі:\n {C}\n")

    # Перевірка умови збіжності: обчислення \| \Phi'(x) \|
    phi_jacobian = np.eye(num_vars) - C @ jacobian(x, funcs, num_vars)  # Якобіан Phi(x)
    norm_phi_jacobian = np.linalg.norm(phi_jacobian, ord=np.inf)  # Обчислення матричної норми (норма ∞)
    print(f"Норма Якобі: {norm_phi_jacobian}")

    # Обчислення максимального значення похідної phi(x) на проміжку [0, 0.5]
    q_max = max(derivative_phi(x, C, funcs,tol), derivative_phi(x + 0.5, C, funcs,tol))
    print(f"Максимальна похідна phi(x) на проміжку [0, 0.5]: {q_max} \n")

    for _ in range(max_iter):
        iterations += 1
        x_new = phi(x, C, funcs)  # Нова ітерація

        # Обчислення критерію зупинки
        stop_criterion =np.linalg.norm(x_new - x)
        print(f"Ітерація {iterations}: x = {x_new}")
        print(f"Критерій зупинки: {stop_criterion} \n")
        C = np.linalg.inv(jacobian(x_new, funcs, num_vars))  # Матриця C
        print(f"Якобіан:\n {C}\n")

        # Перевірка на точність за новим критерієм
        if stop_criterion <= tol:
            print(BORDER)
            return x_new

        x = x_new
    return None  # Якщо не знайдено розв'язок за max_iter ітерацій

# Метод Гауса для розв'язання системи лінійних рівнянь Ax = b
def gauss_solve(A, b):
    n = len(b)
    # Прямий хід: приведення до трикутної форми
    for i in range(n):
        # Пошук максимального елемента у стовпці для часткового вибору головного елемента
        max_row = i + np.argmax(np.abs(A[i:, i]))
        # Перестановка рядків
        A[[i, max_row]] = A[[max_row, i]]
        b[[i, max_row]] = b[[max_row, i]]

        # Нормалізація поточного рядка
        for j in range(i + 1, n):
            factor = A[j, i] / A[i, i]
            A[j, i:] -= factor * A[i, i:]
            b[j] -= factor * b[i]

    # Зворотній хід: обчислення невідомих
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - np.dot(A[i, i + 1:], x[i + 1:])) / A[i, i]
    return x

# Метод Ньютона
def newton_method(x0, funcs, tol=1e-6, max_iter=100):
    print(f"{BORDER} \n {SPACE}Метод Ньютона \n")
    x = np.copy(x0)
    num_vars = len(x)
    for iterations in range(max_iter):
        # Обчислення Якобіана в точці x
        J = jacobian(x, funcs, num_vars)
        # Обчислення значення функції F(x)
        Fx = F(x, funcs)

        # Розв'язання системи A_k z^k = F(x^k) методом Гауса
        z = gauss_solve(J, Fx)

        # Оновлення x: x^{k+1} = x^k - z^k
        x_new = x - z

        stop_criterion = np.linalg.norm(z)
        # Вивід результатів кожної ітерації
        print(f"Ітерація {iterations + 1}: x = {x_new}, ||z|| = {np.linalg.norm(z)}")
        print(f"Критерій зупинки: {stop_criterion} ")
        print(f"Матриця Якобі: \n {J}")
        print(f"Розв'язок СЛАР: {z}\n")

        # Перевірка умови зупинки
        if stop_criterion < tol:
            print(BORDER)
            return x_new

        x = x_new

    print("Метод Ньютона не збігся за вказану кількість ітерацій.")
    return None

# Приклад використання

# Кілька рівнянь для тесту
def f1(x):
    return 2 * x[0] - np.sin((x[0] - x[1]) / 2)

def f2(x):
    return 2 * x[1] - np.cos((x[0] + x[1]) / 2)

# Список функцій для системи рівнянь
funcs = [f1, f2]

# Початкове наближення
x0 = np.array([0, 0.5])

# Запускаємо методи
solution_simple_iteration = simple_iteration_method(x0, funcs, tol=1e-5)
# Запуск методу Ньютона
solution_newton = newton_method(x0, funcs, tol=1e-5)


# Вивід результатів
print("Розв'язок методом простої ітерації:", solution_simple_iteration)
# Вивід результатів
if solution_newton is not None:
    print("Розв'язок методом Ньютона:", solution_newton)
else:
    print("Метод Ньютона не зміг знайти розв'язок.")


------------------------------------------------------------ 
                Метод простої ітерації
Початковий Якобі:
 [[ 0.67234823 -0.15337504]
 [-0.03916349  0.47980951]]

Норма Якобі: 1.8301383718455788e-16
Максимальна похідна phi(x) на проміжку [0, 0.5]: 0.21873634285040827 

Ітерація 1: x = [-0.16157356  0.49477309]
Критерій зупинки: 0.16165807979184715 

Якобіан:
 [[ 0.66319964 -0.15070359]
 [-0.02640052  0.48609528]]

Ітерація 2: x = [-0.16051012  0.49310234]
Критерій зупинки: 0.0019804750037164124 

Якобіан:
 [[ 0.66328583 -0.15080403]
 [-0.02635816  0.48612338]]

Ітерація 3: x = [-0.16050991  0.49310231]
Критерій зупинки: 2.0886495362465268e-07 

Якобіан:
 [[ 0.66328585 -0.15080404]
 [-0.02635818  0.48612337]]

------------------------------------------------------------
------------------------------------------------------------ 
                Метод Ньютона 

Ітерація 1: x = [-0.16157356  0.49477309], ||z|| = 0.16165807979184715
Критерій зупинки: 0.16165807979184715 
Мат

In [ ]:
q_max = max(derivative_phi(x,C,funcs,tol))

def derivative_phi(x, C, funcs, h=1e-5):
    # Обчислюємо phi(x) для поточної точки
    phi_x = phi(x, C, funcs)

    # Обчислюємо phi(x + h) для кожної змінної окремо
    phi_x_h = np.array([phi(x + h * np.eye(len(x))[i], C, funcs) for i in range(len(x))])

    # Вираховуємо похідні
    derivatives = (phi_x_h - phi_x) / h

    # Повертаємо норму (для кожної змінної окремо)
    return np.linalg.norm(derivatives, axis=1)
