<a href="https://colab.research.google.com/github/Recollectionss/University/blob/main/4-course/1-sem/eemp/lab-5/eemp-lab5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
from numpy.linalg import inv, eig, matrix_power, solve, norm

# ============================================
#                 7.1
# ============================================

print("=== 7.1. ДВОСЕКТОРНА МОДЕЛЬ ===")

x1_prev = 800 + 400 + 800
x2_prev = 300 + 350 + 600

# Матриця прямих витрат A (рядки — постачальники, стовпці — споживачі)
A2 = np.array([
    [800/x1_prev, 400/x2_prev],
    [300/x1_prev, 350/x2_prev]
])

print("Матриця прямих витрат A:\n", np.round(A2, 4))

# Попит
y = np.array([1100, 850], dtype=float)

# Матриця повних витрат
I2 = np.eye(2)
B2 = inv(I2 - A2)


x_new = B2 @ y

print("\nМатриця повних витрат B:\n", np.round(B2, 4))
print("\nНовий повний випуск:")
print(f"Промисловість = {x_new[0]:.2f} млн грн")
print(f"С/г = {x_new[1]:.2f} млн грн")

# ============================================
#                 7.2
# ============================================

print("\n\n=== 7.2. МАТРИЧНА МОДЕЛЬ (3×3) ===")

A = np.array([
    [0.4, 0.1, 0.5],
    [0.1, 0.6, 0.3],
    [0.5, 0.3, 0.2]
])

print("Матриця A:\n", A)

eigvals, eigvecs = eig(A)
print("\nВласні числа матриці A:")
for i, val in enumerate(eigvals):
    print(f"λ{i+1} = {val:.6f}")

# --- Характеристичний поліном ---
char_poly = np.poly(A)
print("\nКоефіцієнти характеристичного полінома (від x^3 до вільного члена):")
print(np.round(char_poly, 6))

# --- Число Фробеніуса ---
rho = max(abs(eigvals))
idx = np.argmax(abs(eigvals))
lambda_pf = eigvals[idx]

right_pf = eigvecs[:, idx].real
right_pf /= right_pf.sum()

left_vals, left_vecs = eig(A.T)
idx_L = np.argmax(abs(left_vals))
left_pf = left_vecs[:, idx_L].real
left_pf /= left_pf.sum()

print("\nЧисло Фробеніуса (спектральний радіус):", round(rho, 6))
print("Правий PF-вектор (нормований):", np.round(right_pf, 4))
print("Лівий PF-вектор (нормований):", np.round(left_pf, 4))

# --- Матриця повних витрат B ---
I3 = np.eye(3)
B = inv(I3 - A)
print("\nМатриця повних витрат B:\n", np.round(B, 4))

# --- Збіжність ряду E + A + A^2 + ... ---
print("\nПеревірка збіжності ряду:")

S = np.eye(3)
for n in range(1, 50):
    S += matrix_power(A, n)
    if np.max(abs(S - B)) < 0.01:
        print(f"Ряд збігається до B при N = {n}")
        break

print("\nS(N):\n", np.round(S, 4))
print("\nB:\n", np.round(B, 4))

s = np.array([0.4, 0.3, 0.6], dtype=float)
p = s @ B

print("\nВектор цін p:")
print(np.round(p, 4))


=== 7.1. ДВОСЕКТОРНА МОДЕЛЬ ===
Матриця прямих витрат A:
 [[0.4  0.32]
 [0.15 0.28]]

Матриця повних витрат B:
 [[1.875  0.8333]
 [0.3906 1.5625]]

Новий повний випуск:
Промисловість = 2770.83 млн грн
С/г = 1757.81 млн грн


=== 7.2. МАТРИЧНА МОДЕЛЬ (3×3) ===
Матриця A:
 [[0.4 0.1 0.5]
 [0.1 0.6 0.3]
 [0.5 0.3 0.2]]

Власні числа матриці A:
λ1 = -0.246410
λ2 = 1.000000
λ3 = 0.446410

Коефіцієнти характеристичного полінома (від x^3 до вільного члена):
[ 1.   -1.2   0.09  0.11]

Число Фробеніуса (спектральний радіус): 1.0
Правий PF-вектор (нормований): [0.3333 0.3333 0.3333]
Лівий PF-вектор (нормований): [0.3333 0.3333 0.3333]

Матриця повних витрат B:
 [[9.00719925e+15 9.00719925e+15 9.00719925e+15]
 [9.00719925e+15 9.00719925e+15 9.00719925e+15]
 [9.00719925e+15 9.00719925e+15 9.00719925e+15]]

Перевірка збіжності ряду:

S(N):
 [[17.5362 15.942  16.5217]
 [15.942  17.8261 16.2319]
 [16.5217 16.2319 17.2464]]

B:
 [[9.00719925e+15 9.00719925e+15 9.00719925e+15]
 [9.00719925e+15 9.007199